name: roadblock-ci

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/crucible-merged.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-roadblock-ci.yaml
    - .github/workflows/faux-pylint.yaml
    - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/roadblock-ci
  cancel-in-progress: true

jobs:
  roadblock-ci-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tests:
        - name: "Run small roadblock test"
          args: "--followers 5"
        - name: "Run roadblock timeout test"
          args: "--followers 5 --timeout"
        - name: "Run roadblock abort test"
          args: "--followers 5 --abort"
        - name: "Run large roadblock test"
          args: "--followers 50"
        - name: "Run wait-for test"
          args: "--followers 5 --wait-for"
        - name: "Run wait-for heartbeat timeout test"
          args: "--followers 5 --wait-for-heartbeat-timeout"
        - name: "Run wait-for abort test"
          args: "--followers 5 --wait-for-abort"
        - name: "Run 1 Leader SIGINT (abort) test"
          args: "--followers 5 --leader-sigints 1"
        - name: "Run 2 Leader SIGINT (exit) test"
          args: "--followers 5 --leader-sigints 2"

    steps:
    - name: Matrix Parameters => ("${{ matrix.tests.name }}", "${{ matrix.tests.args }}")
      run: |
        echo "name=\"${{ matrix.tests.name }}\""
        echo "args=\"${{ matrix.tests.args }}\""

    - uses: actions/checkout@v4

    - name: Install test dependencies
      run: |
        . /etc/os-release
        sudo apt-get -y install podman
        sudo apt-get -y install buildah

    - name: Build roadblock container
      run: |
        sudo ./test/build-container.sh

    - name: ${{ matrix.tests.name }}
      run: |
        sudo ./test/run-test.sh ${{ matrix.tests.args }}

  roadblock-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]

    needs:
    - roadblock-ci-tests

    steps:
    - name: Confirm Success
      run: echo "roadblock-ci-complete"
